# SPDX-License-Identifier: GPL-2.0
#
# Makefile for ALSA
# Copyright (c) 2001 by Jaroslav Kysela <perex@perex.cz>
#

snd-intel8x0-y := intel8x0.o
snd-intel8x0m-y := intel8x0m.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_INTEL8X0) += snd-intel8x0.o
obj-$(CONFIG_SND_INTEL8X0M) += snd-intel8x0m.o

obj-$(CONFIG_SND) += \
	echoaudio/
